### PR TITLE
Using EditorConfig for customization

### PR DESCRIPTION
**Pull request by DecimalTurn**
This PR is trying to implement my suggestion from here : https://github.com/Beakerboy/VBA-Linter/discussions/52#discussioncomment-7911476

It still needs some work, but it's a good illustration of how the approach I'm suggesting would look like.

### CODE REVIEW

**Comment by Beakerboy** [comment]
To me, it looks like editor config aims to provide very basic linting options, but for nearly any programming language. I am trying to create some thing that targets, one language, but coding style options for lots of people. I’m concerned that if I use the editorconfig file, users will expect all of the features that editorconfig provides out of the box. One of the options that is highlighted is the choice of line endings. As far as I know, all VBA files must have CRLF line endings I probably would not want to honor that setting.

Another thing that jumped out at me, was the fact that there is a star.PY within the example file that you have included in this whole request. Shouldn’t this of the file have bas ,cls and frm as the file types?

**Comment by DecimalTurn** [comment]
> One of the options that is highlighted is the choice of line endings. As far as I know, all VBA files must have CRLF line endings I probably would not want to honor that setting.

I would have said the same thing as you not so long ago, but after reading what you wrote in [your comment](https://github.com/Beakerboy/VBA-SQL-Library/issues/56#issuecomment-1835925668), I started to doubt that we should force people to store VBA code with a specific line ending on GitHub.

If you think that the linter should be more opinated and enforce certains configurations, then a standalone .toml file is probably the way to go.

> Another thing that jumped out at me, was the fact that there is a star.PY within the example file that you have included in this whole request. Shouldn’t this of the file have bas ,cls and frm as the file types?

The editorconfig file included in the Draft PR isn't an example, it's an actual suggestion of an editorconfig file for this python package. I just thought that if we are going to make VBA repos use the editorconfig file, we might as well use it in the python package itself. 

However, this is optional and if you don't want it here, I can remove it from the PR. 

What I would consider an example editorconfig file for a VBA project would be this instead:

```editorconfig

# EditorConfig is awesome: http://EditorConfig.org

# top-most EditorConfig file
root = true

[*.{bas,cls,frm}]
indent_style = space
indent_size = 4
end_of_line = crlf
charset = windows-1252
# https://learn.microsoft.com/en-us/office/vba/language/reference/user-interface-help/line-too-long
max_line_length = 1023
insert_final_newline = true
trim_trailing_whitespace = true

```

**Comment by Beakerboy** [comment]
I’m not a “python programmer” per-se, but I’ve only ever seen flake8 used as the linter of choice for python projects. Python has well defined standards for code quality, and flake8 makes sure code meets the PEP8 standard. It also works well with the static type checker, mypy.

**Comment by DecimalTurn** [comment]
The goal of this PR was not to introduce an .editorconfig file for this project, so I'm not going to try and give other justifications why it could be useful. I should have deleleted it before making the PR.

Regarding the way to customize the linter, I'm ok with another format, so I'll close.

**Comment by Beakerboy** [comment]
Thanks for the suggestion. I actually like the idea of a toml file. I was planning on using yml, but after looking into it, that’s probably the better option. The way I see it, the VBA editor that comes with excel is cannon. It disallows tabs as whitespace, it uses CRLF, forces only one space after commas, etc. these things should be required by a rule-set. Beyond these forced rules, we should allow users to set parameters for things that can be changed, and turn on and off those rules if they do not want to use them.

**Pull request closed without merging**
